'use strict';

/**
 * Référentiel métier : types d'opérations, schéma des variables (saisies UNE
 * SEULE FOIS par opération), checklists de documents et contenu des templates.
 *
 * Syntaxe des templates (docxtemplater) :
 *   {variable}                 substitution simple
 *   {#condition}...{/condition}  bloc conditionnel (clause optionnelle)
 *   {^condition}...{/condition}  bloc inverse (si condition absente)
 *   {#liste}...{/liste}        boucle sur une liste (associés, souscripteurs…)
 *
 * Variables auto-injectées depuis la fiche société (jamais resaisies) :
 *   societe_denomination, societe_forme, societe_capital, societe_siege,
 *   societe_siren, societe_rcs, societe_nb_titres, dirigeant_nom_complet,
 *   dirigeant_fonction, dirigeant_adresse, associes[] (nom_complet, nb_titres,
 *   pourcentage, adresse), date_jour
 *
 * Chaque bloc de template : { style, text }
 *   styles : title | h1 | h2 | p | center | right | sign
 */

const EN_TETE_SOCIETE = [
  { style: 'center', text: '{societe_denomination}' },
  { style: 'center', text: '{societe_forme} au capital de {societe_capital} euros' },
  { style: 'center', text: 'Siège social : {societe_siege}' },
  { style: 'center', text: '{societe_siren} RCS {societe_rcs}' },
  { style: 'p', text: '' },
];

const OPERATION_TYPES = {
  /* ------------------------------------------------------------------ */
  constitution: {
    libelle: 'Constitution de société',
    variables: [
      { name: 'date_signature', label: 'Date de signature des statuts', type: 'date', required: true },
      { name: 'duree_societe', label: 'Durée de la société (années)', type: 'number', default: 99, required: true },
      { name: 'valeur_nominale', label: 'Valeur nominale des titres (€)', type: 'number', required: true },
      { name: 'depositaire_fonds', label: 'Banque dépositaire des fonds', type: 'text', required: true },
      { name: 'clause_agrement', label: "Clause d'agrément des cessions", type: 'checkbox', default: true },
      { name: 'souscripteurs', label: 'Souscripteurs', type: 'list', required: true, fields: [
        { name: 'nom_complet', label: 'Nom complet / dénomination', type: 'text' },
        { name: 'adresse', label: 'Adresse', type: 'text' },
        { name: 'nb_titres', label: 'Titres souscrits', type: 'number' },
        { name: 'apport', label: 'Apport (€)', type: 'number' },
      ] },
    ],
    documents: [
      {
        code: 'statuts', nom: 'Statuts constitutifs', obligatoire: true,
        template: [
          { style: 'title', text: '{societe_denomination}' },
          { style: 'center', text: '{societe_forme} au capital de {societe_capital} euros' },
          { style: 'center', text: 'Siège social : {societe_siege}' },
          { style: 'p', text: '' },
          { style: 'title', text: 'STATUTS' },
          { style: 'p', text: 'Les soussignés :' },
          { style: 'p', text: '{#souscripteurs}' },
          { style: 'p', text: '- {nom_complet}, demeurant {adresse}, souscrivant {nb_titres} titres pour un apport de {apport_fmt} euros ;' },
          { style: 'p', text: '{/souscripteurs}' },
          { style: 'p', text: "ont établi ainsi qu'il suit les statuts de la société qu'ils sont convenus de constituer." },
          { style: 'h1', text: 'Article 1 — Forme' },
          { style: 'p', text: 'Il est formé entre les soussignés une {societe_forme} régie par les dispositions du Code de commerce et par les présents statuts.' },
          { style: 'h1', text: 'Article 2 — Dénomination' },
          { style: 'p', text: 'La dénomination sociale est : {societe_denomination}.' },
          { style: 'h1', text: 'Article 3 — Objet' },
          { style: 'p', text: 'La société a pour objet, en France et à l’étranger : {societe_objet}.' },
          { style: 'h1', text: 'Article 4 — Siège social' },
          { style: 'p', text: 'Le siège social est fixé : {societe_siege}.' },
          { style: 'h1', text: 'Article 5 — Durée' },
          { style: 'p', text: 'La durée de la société est fixée à {duree_societe} années à compter de son immatriculation au registre du commerce et des sociétés, sauf dissolution anticipée ou prorogation.' },
          { style: 'h1', text: 'Article 6 — Apports et capital social' },
          { style: 'p', text: 'Le capital social est fixé à la somme de {societe_capital} euros, divisé en {societe_nb_titres} titres de {valeur_nominale_fmt} euro(s) de valeur nominale chacun, intégralement souscrits et libérés en numéraire.' },
          { style: 'p', text: 'Les fonds correspondant aux apports en numéraire ont été déposés auprès de {depositaire_fonds}.' },
          { style: 'h1', text: 'Article 7 — Cessions de titres' },
          { style: 'p', text: '{#clause_agrement}' },
          { style: 'p', text: "Toute cession de titres, y compris entre associés, est soumise à l'agrément préalable de la collectivité des associés statuant à la majorité des voix des associés disposant du droit de vote." },
          { style: 'p', text: '{/clause_agrement}' },
          { style: 'p', text: '{^clause_agrement}' },
          { style: 'p', text: 'Les titres se transmettent librement.' },
          { style: 'p', text: '{/clause_agrement}' },
          { style: 'h1', text: 'Article 8 — Direction' },
          { style: 'p', text: 'La société est dirigée par un {dirigeant_fonction}, personne physique ou morale, associé ou non, nommé par décision collective des associés.' },
          { style: 'p', text: 'Est nommé en qualité de premier {dirigeant_fonction} : {dirigeant_nom_complet}, demeurant {dirigeant_adresse}, pour une durée illimitée.' },
          { style: 'h1', text: 'Article 9 — Décisions collectives' },
          { style: 'p', text: "Les décisions collectives des associés sont prises, au choix de la direction, en assemblée, par consultation écrite ou par acte unanime. Chaque titre donne droit à une voix." },
          { style: 'h1', text: 'Article 10 — Exercice social' },
          { style: 'p', text: "L'exercice social commence le 1er janvier et se termine le {societe_cloture} de chaque année." },
          { style: 'p', text: '' },
          { style: 'p', text: 'Fait à {societe_rcs}, le {date_signature_fmt}, en autant d’exemplaires que de parties.' },
          { style: 'p', text: '{#souscripteurs}' },
          { style: 'sign', text: '{nom_complet}' },
          { style: 'p', text: '{/souscripteurs}' },
        ],
      },
      {
        code: 'liste_souscripteurs', nom: 'Liste des souscripteurs', obligatoire: true,
        template: [
          ...EN_TETE_SOCIETE,
          { style: 'title', text: 'LISTE DES SOUSCRIPTEURS' },
          { style: 'p', text: 'Établie conformément à l’article R. 224-3 du Code de commerce.' },
          { style: 'p', text: '{#souscripteurs}' },
          { style: 'p', text: '{nom_complet}, demeurant {adresse} — {nb_titres} titres souscrits — versement : {apport_fmt} euros.' },
          { style: 'p', text: '{/souscripteurs}' },
          { style: 'p', text: 'Total : {societe_nb_titres} titres, soit {societe_capital} euros.' },
          { style: 'p', text: 'Fait le {date_signature_fmt}.' },
          { style: 'sign', text: '{dirigeant_nom_complet}, {dirigeant_fonction}' },
        ],
      },
      {
        code: 'dnc', nom: 'Déclaration de non-condamnation du dirigeant', obligatoire: true,
        template: [
          { style: 'title', text: 'DÉCLARATION SUR L’HONNEUR DE NON-CONDAMNATION ET DE FILIATION' },
          { style: 'p', text: 'Je soussigné(e) {dirigeant_nom_complet}, demeurant {dirigeant_adresse},' },
          { style: 'p', text: 'déclare sur l’honneur, conformément à l’article A. 123-51 du Code de commerce, n’avoir fait l’objet d’aucune condamnation pénale ni sanction civile ou administrative de nature à m’interdire de gérer, administrer ou diriger une personne morale, ou d’exercer une activité commerciale.' },
          { style: 'p', text: 'Cette déclaration est établie en vue de ma nomination en qualité de {dirigeant_fonction} de la société {societe_denomination}, {societe_forme} en cours de constitution dont le siège social est situé {societe_siege}.' },
          { style: 'p', text: 'Fait le {date_signature_fmt}.' },
          { style: 'sign', text: '{dirigeant_nom_complet}' },
        ],
      },
      {
        code: 'pouvoir_formalites', nom: 'Pouvoir pour les formalités', obligatoire: true,
        template: [
          { style: 'title', text: 'POUVOIR' },
          { style: 'p', text: 'Je soussigné(e) {dirigeant_nom_complet}, agissant en qualité de {dirigeant_fonction} de la société {societe_denomination}, {societe_forme} en cours de constitution au capital de {societe_capital} euros, dont le siège social est situé {societe_siege},' },
          { style: 'p', text: 'donne tous pouvoirs au porteur d’un original, d’une copie ou d’un extrait des présentes à l’effet d’accomplir toutes formalités de publicité, de dépôt et d’immatriculation prescrites par la loi.' },
          { style: 'p', text: 'Fait le {date_signature_fmt}.' },
          { style: 'sign', text: '{dirigeant_nom_complet}' },
        ],
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  cession_titres: {
    libelle: 'Cession de titres',
    variables: [
      { name: 'cedant_nom', label: 'Cédant — nom complet', type: 'text', required: true },
      { name: 'cedant_adresse', label: 'Cédant — adresse', type: 'text', required: true },
      { name: 'cessionnaire_nom', label: 'Cessionnaire — nom complet', type: 'text', required: true },
      { name: 'cessionnaire_adresse', label: 'Cessionnaire — adresse', type: 'text', required: true },
      { name: 'nb_titres_cedes', label: 'Nombre de titres cédés', type: 'number', required: true },
      { name: 'prix_total', label: 'Prix de cession total (€)', type: 'number', required: true },
      { name: 'date_cession', label: 'Date de la cession', type: 'date', required: true },
      { name: 'clause_agrement', label: 'Agrément préalable requis par les statuts', type: 'checkbox', default: true },
      { name: 'garantie_ap', label: "Convention de garantie d'actif et de passif", type: 'checkbox', default: false },
      { name: 'date_agrement', label: "Date de la décision d'agrément", type: 'date', showIf: 'clause_agrement' },
    ],
    documents: [
      {
        code: 'acte_cession', nom: 'Acte de cession de titres', obligatoire: true,
        template: [
          { style: 'title', text: 'ACTE DE CESSION DE TITRES' },
          { style: 'h2', text: 'Entre les soussignés :' },
          { style: 'p', text: '{cedant_nom}, demeurant {cedant_adresse}, ci-après désigné le « Cédant »,' },
          { style: 'p', text: 'et' },
          { style: 'p', text: '{cessionnaire_nom}, demeurant {cessionnaire_adresse}, ci-après désigné le « Cessionnaire »,' },
          { style: 'p', text: 'il a été convenu ce qui suit au sujet des titres de la société {societe_denomination}, {societe_forme} au capital de {societe_capital} euros, dont le siège social est situé {societe_siege}, immatriculée sous le numéro {societe_siren} RCS {societe_rcs} (la « Société »).' },
          { style: 'h1', text: 'Article 1 — Cession' },
          { style: 'p', text: 'Le Cédant cède au Cessionnaire, qui accepte, {nb_titres_cedes} titres de la Société, avec tous les droits qui y sont attachés, à compter du {date_cession_fmt}.' },
          { style: 'h1', text: 'Article 2 — Prix' },
          { style: 'p', text: 'La cession est consentie et acceptée moyennant un prix global et forfaitaire de {prix_total_fmt} euros, soit {prix_unitaire_fmt} euros par titre, que le Cédant reconnaît avoir reçu ce jour du Cessionnaire, dont quittance.' },
          { style: 'p', text: '{#clause_agrement}' },
          { style: 'h1', text: 'Article 3 — Agrément' },
          { style: 'p', text: "La présente cession a été agréée par décision collective des associés de la Société en date du {date_agrement_fmt}, conformément aux stipulations statutaires." },
          { style: 'p', text: '{/clause_agrement}' },
          { style: 'p', text: '{#garantie_ap}' },
          { style: 'h1', text: "Garantie d'actif et de passif" },
          { style: 'p', text: "Concomitamment aux présentes, les parties ont conclu une convention de garantie d'actif et de passif qui demeure annexée au présent acte." },
          { style: 'p', text: '{/garantie_ap}' },
          { style: 'h1', text: 'Formalités — Opposabilité' },
          { style: 'p', text: "La cession sera rendue opposable à la Société par la signature d'un ordre de mouvement et son inscription dans les registres de la Société. Tous pouvoirs sont donnés au porteur d'un original des présentes pour l'accomplissement des formalités d'enregistrement." },
          { style: 'p', text: 'Fait le {date_cession_fmt}, en deux exemplaires originaux.' },
          { style: 'sign', text: 'Le Cédant : {cedant_nom}' },
          { style: 'sign', text: 'Le Cessionnaire : {cessionnaire_nom}' },
        ],
      },
      {
        code: 'ordre_mouvement', nom: 'Ordre de mouvement', obligatoire: true,
        template: [
          ...EN_TETE_SOCIETE,
          { style: 'title', text: 'ORDRE DE MOUVEMENT' },
          { style: 'p', text: 'Le soussigné {cedant_nom}, demeurant {cedant_adresse}, donne ordre à la société {societe_denomination} de virer, par voie de cession, du compte du soussigné au compte de {cessionnaire_nom}, demeurant {cessionnaire_adresse} :' },
          { style: 'center', text: '{nb_titres_cedes} titres' },
          { style: 'p', text: 'Nature du transfert : cession. Date d’effet : {date_cession_fmt}.' },
          { style: 'sign', text: 'Le titulaire des titres : {cedant_nom}' },
        ],
      },
      {
        code: 'pv_agrement', nom: "PV d'agrément de la cession", obligatoire: false, condition: 'clause_agrement',
        template: [
          ...EN_TETE_SOCIETE,
          { style: 'title', text: 'PROCÈS-VERBAL DES DÉCISIONS COLLECTIVES DES ASSOCIÉS' },
          { style: 'center', text: 'En date du {date_agrement_fmt}' },
          { style: 'p', text: "Les associés de la société {societe_denomination}, représentant la totalité du capital et des droits de vote, ont pris la décision suivante sur convocation de {dirigeant_nom_complet}, {dirigeant_fonction}." },
          { style: 'h1', text: 'Décision unique — Agrément de cession de titres' },
          { style: 'p', text: "La collectivité des associés, connaissance prise du projet de cession par {cedant_nom} de {nb_titres_cedes} titres de la Société au profit de {cessionnaire_nom}, au prix global de {prix_total_fmt} euros, agrée expressément ladite cession en application des stipulations statutaires." },
          { style: 'p', text: 'Cette décision est adoptée à l’unanimité.' },
          { style: 'p', text: "De tout ce que dessus, il a été dressé le présent procès-verbal, signé après lecture." },
          { style: 'sign', text: '{dirigeant_nom_complet}, {dirigeant_fonction}' },
        ],
      },
      {
        code: 'gap', nom: "Convention de garantie d'actif et de passif", obligatoire: false, condition: 'garantie_ap',
        template: [
          { style: 'title', text: "CONVENTION DE GARANTIE D'ACTIF ET DE PASSIF" },
          { style: 'p', text: 'Entre {cedant_nom} (le « Garant ») et {cessionnaire_nom} (le « Bénéficiaire »), relative à la cession de {nb_titres_cedes} titres de la société {societe_denomination} intervenue le {date_cession_fmt} au prix de {prix_total_fmt} euros.' },
          { style: 'h1', text: 'Article 1 — Déclarations du Garant' },
          { style: 'p', text: "Le Garant déclare que les comptes de la Société sont réguliers et sincères, que la Société est propriétaire de ses actifs, à jour de ses obligations fiscales et sociales, et qu'il n'existe aucun litige non provisionné à la date de cession." },
          { style: 'h1', text: 'Article 2 — Garantie' },
          { style: 'p', text: "Le Garant indemnisera le Bénéficiaire de tout passif supplémentaire ou insuffisance d'actif trouvant son origine antérieurement à la date de cession et révélé postérieurement à celle-ci." },
          { style: 'h1', text: 'Article 3 — Durée et plafond' },
          { style: 'p', text: 'La présente garantie est consentie pour une durée de trois ans (prescription fiscale et sociale non écoulée réservée) et plafonnée au prix de cession, soit {prix_total_fmt} euros.' },
          { style: 'p', text: 'Fait le {date_cession_fmt}, en deux exemplaires.' },
          { style: 'sign', text: 'Le Garant : {cedant_nom}' },
          { style: 'sign', text: 'Le Bénéficiaire : {cessionnaire_nom}' },
        ],
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  augmentation_capital: {
    libelle: 'Augmentation de capital',
    variables: [
      { name: 'date_age', label: "Date de l'assemblée générale extraordinaire", type: 'date', required: true },
      { name: 'montant_augmentation', label: "Montant nominal de l'augmentation (€)", type: 'number', required: true },
      { name: 'nb_titres_nouveaux', label: 'Nombre de titres nouveaux', type: 'number', required: true },
      { name: 'prix_emission', label: "Prix d'émission par titre, prime incluse (€)", type: 'number', required: true },
      { name: 'suppression_dps', label: 'Suppression du droit préférentiel de souscription', type: 'checkbox', default: false },
      { name: 'date_limite_souscription', label: 'Date limite de souscription', type: 'date', required: true },
      { name: 'souscripteurs', label: 'Souscripteurs', type: 'list', required: true, fields: [
        { name: 'nom_complet', label: 'Nom complet / dénomination', type: 'text' },
        { name: 'adresse', label: 'Adresse', type: 'text' },
        { name: 'nb_titres', label: 'Titres souscrits', type: 'number' },
        { name: 'montant', label: 'Versement (€)', type: 'number' },
      ] },
    ],
    documents: [
      {
        code: 'pv_age', nom: "PV d'AGE décidant l'augmentation", obligatoire: true,
        template: [
          ...EN_TETE_SOCIETE,
          { style: 'title', text: 'PROCÈS-VERBAL DE L’ASSEMBLÉE GÉNÉRALE EXTRAORDINAIRE' },
          { style: 'center', text: 'Du {date_age_fmt}' },
          { style: 'p', text: "L'an et le jour susdits, les associés de la société {societe_denomination} se sont réunis en assemblée générale extraordinaire au siège social, sur convocation de {dirigeant_nom_complet}, {dirigeant_fonction}, à l'effet de délibérer sur l'ordre du jour suivant :" },
          { style: 'p', text: '- Augmentation du capital social en numéraire ;' },
          { style: 'p', text: '{#suppression_dps}- Suppression du droit préférentiel de souscription ;{/suppression_dps}' },
          { style: 'p', text: '- Modification corrélative des statuts ; pouvoirs pour formalités.' },
          { style: 'h1', text: 'Première résolution — Augmentation de capital' },
          { style: 'p', text: "L'assemblée générale décide d'augmenter le capital social d'un montant nominal de {montant_augmentation_fmt} euros, pour le porter de {societe_capital} euros à {capital_apres_fmt} euros, par l'émission de {nb_titres_nouveaux} titres nouveaux au prix unitaire de {prix_emission_fmt} euros, prime d'émission incluse, à libérer intégralement en numéraire lors de la souscription, au plus tard le {date_limite_souscription_fmt}." },
          { style: 'p', text: 'Cette résolution est adoptée à l’unanimité.' },
          { style: 'p', text: '{#suppression_dps}' },
          { style: 'h1', text: 'Deuxième résolution — Suppression du droit préférentiel de souscription' },
          { style: 'p', text: "L'assemblée générale décide de supprimer le droit préférentiel de souscription des associés au profit des personnes désignées dans le rapport de la direction, dans les conditions de l'article L. 225-138 du Code de commerce applicable sur renvoi." },
          { style: 'p', text: 'Cette résolution est adoptée à l’unanimité, les bénéficiaires ne prenant pas part au vote.' },
          { style: 'p', text: '{/suppression_dps}' },
          { style: 'h1', text: 'Résolution finale — Pouvoirs' },
          { style: 'p', text: "Tous pouvoirs sont conférés au {dirigeant_fonction} à l'effet de recueillir les souscriptions et versements, de constater la réalisation définitive de l'augmentation de capital, de modifier corrélativement les statuts et d'accomplir toutes formalités." },
          { style: 'p', text: "Plus rien n'étant à l'ordre du jour, la séance est levée. De tout ce que dessus, il a été dressé le présent procès-verbal signé après lecture." },
          { style: 'sign', text: '{dirigeant_nom_complet}, {dirigeant_fonction}' },
        ],
      },
      {
        code: 'bulletin_souscription', nom: 'Bulletins de souscription', obligatoire: true,
        template: [
          ...EN_TETE_SOCIETE,
          { style: 'title', text: 'BULLETIN DE SOUSCRIPTION' },
          { style: 'p', text: '{#souscripteurs}' },
          { style: 'p', text: 'Je soussigné(e) {nom_complet}, demeurant {adresse}, connaissance prise de la décision de l’assemblée générale extraordinaire du {date_age_fmt} de la société {societe_denomination} d’augmenter son capital, déclare souscrire {nb_titres} titres nouveaux au prix unitaire de {prix_emission_fmt} euros et verser à l’appui de ma souscription la somme de {montant_fmt} euros.' },
          { style: 'sign', text: '{nom_complet} — Bon pour souscription' },
          { style: 'p', text: '{/souscripteurs}' },
          { style: 'p', text: 'Souscriptions à recevoir au plus tard le {date_limite_souscription_fmt}.' },
        ],
      },
      {
        code: 'pv_constatation', nom: 'PV de constatation de la réalisation', obligatoire: true,
        template: [
          ...EN_TETE_SOCIETE,
          { style: 'title', text: 'DÉCISION DU {dirigeant_fonction_maj} CONSTATANT LA RÉALISATION DE L’AUGMENTATION DE CAPITAL' },
          { style: 'p', text: "Le soussigné {dirigeant_nom_complet}, {dirigeant_fonction} de la société {societe_denomination}, agissant en vertu des pouvoirs conférés par l'assemblée générale extraordinaire du {date_age_fmt}," },
          { style: 'p', text: "constate que les {nb_titres_nouveaux} titres nouveaux émis ont été intégralement souscrits et libérés pour un montant total de {total_souscrit_fmt} euros, ainsi qu'il résulte des bulletins de souscription et du certificat du dépositaire," },
          { style: 'p', text: "et en conséquence que l'augmentation de capital d'un montant nominal de {montant_augmentation_fmt} euros est définitivement réalisée à la date des présentes, le capital social étant désormais fixé à {capital_apres_fmt} euros." },
          { style: 'p', text: "Les statuts sont modifiés corrélativement." },
          { style: 'sign', text: '{dirigeant_nom_complet}, {dirigeant_fonction}' },
        ],
      },
      {
        code: 'statuts_modifies', nom: 'Statuts mis à jour (article capital)', obligatoire: true,
        template: [
          ...EN_TETE_SOCIETE,
          { style: 'title', text: 'STATUTS MIS À JOUR — EXTRAIT' },
          { style: 'h1', text: 'Article 6 — Capital social (nouvelle rédaction)' },
          { style: 'p', text: 'Le capital social est fixé à la somme de {capital_apres_fmt} euros, divisé en {nb_titres_apres} titres intégralement souscrits et libérés.' },
          { style: 'p', text: 'Statuts mis à jour suite à la décision de l’assemblée générale extraordinaire du {date_age_fmt} et à la constatation de la réalisation de l’augmentation de capital.' },
          { style: 'p', text: 'Copie certifiée conforme.' },
          { style: 'sign', text: '{dirigeant_nom_complet}, {dirigeant_fonction}' },
        ],
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  pacte_associes: {
    libelle: "Pacte d'associés",
    variables: [
      { name: 'date_pacte', label: 'Date de signature du pacte', type: 'date', required: true },
      { name: 'duree_pacte', label: 'Durée du pacte (années)', type: 'number', default: 10, required: true },
      { name: 'clause_preemption', label: 'Droit de préemption', type: 'checkbox', default: true },
      { name: 'clause_inalienabilite', label: "Inaliénabilité temporaire", type: 'checkbox', default: false },
      { name: 'duree_inalienabilite', label: "Durée d'inaliénabilité (années)", type: 'number', default: 3, showIf: 'clause_inalienabilite' },
      { name: 'clause_drag', label: 'Obligation de sortie conjointe (drag along)', type: 'checkbox', default: true },
      { name: 'clause_tag', label: 'Droit de sortie conjointe (tag along)', type: 'checkbox', default: true },
      { name: 'clause_non_concurrence', label: 'Non-concurrence des associés opérationnels', type: 'checkbox', default: false },
      { name: 'parties', label: 'Parties au pacte', type: 'list', required: true, fields: [
        { name: 'nom_complet', label: 'Nom complet / dénomination', type: 'text' },
        { name: 'adresse', label: 'Adresse', type: 'text' },
        { name: 'nb_titres', label: 'Titres détenus', type: 'number' },
      ] },
    ],
    documents: [
      {
        code: 'pacte', nom: "Pacte d'associés", obligatoire: true,
        template: [
          { style: 'title', text: 'PACTE D’ASSOCIÉS' },
          { style: 'center', text: 'Société {societe_denomination}' },
          { style: 'h2', text: 'Entre les soussignés :' },
          { style: 'p', text: '{#parties}' },
          { style: 'p', text: '- {nom_complet}, demeurant {adresse}, titulaire de {nb_titres} titres ;' },
          { style: 'p', text: '{/parties}' },
          { style: 'p', text: 'ci-après ensemble les « Parties », associés de la société {societe_denomination}, {societe_forme} au capital de {societe_capital} euros, siège social {societe_siege}, {societe_siren} RCS {societe_rcs} (la « Société »).' },
          { style: 'h1', text: 'Article 1 — Objet et durée' },
          { style: 'p', text: "Le présent pacte a pour objet d'organiser les relations entre les Parties en leur qualité d'associés de la Société. Il est conclu pour une durée de {duree_pacte} années à compter du {date_pacte_fmt}, renouvelable par accord exprès des Parties. Il cesse de plein droit à l'égard de toute Partie qui perd la qualité d'associé." },
          { style: 'p', text: '{#clause_inalienabilite}' },
          { style: 'h1', text: 'Article — Inaliénabilité' },
          { style: 'p', text: "Chaque Partie s'interdit de céder ou transférer ses titres, sous quelque forme que ce soit, pendant une durée de {duree_inalienabilite} années à compter de la signature du présent pacte, sauf accord unanime et écrit des autres Parties. Cette durée est conforme à l'exigence de proportionnalité au regard de l'intérêt social." },
          { style: 'p', text: '{/clause_inalienabilite}' },
          { style: 'p', text: '{#clause_preemption}' },
          { style: 'h1', text: 'Article — Droit de préemption' },
          { style: 'p', text: "Toute Partie envisageant de céder tout ou partie de ses titres à un tiers ou à une autre Partie notifiera son projet aux autres Parties (identité du cessionnaire, nombre de titres, prix et conditions). Les autres Parties disposeront d'un délai de trente (30) jours pour exercer leur droit de préemption, au prix notifié, au prorata de leur participation. À défaut d'exercice total, le cédant pourra réaliser la cession projetée aux conditions notifiées dans un délai de soixante (60) jours." },
          { style: 'p', text: '{/clause_preemption}' },
          { style: 'p', text: '{#clause_tag}' },
          { style: 'h1', text: 'Article — Droit de sortie conjointe (tag along)' },
          { style: 'p', text: "En cas de projet de cession entraînant un transfert du contrôle de la Société, chaque Partie non cédante pourra exiger que le cessionnaire acquière simultanément la totalité de ses titres aux mêmes conditions, notamment de prix, que celles offertes au cédant. À défaut, la cession projetée ne pourra être réalisée." },
          { style: 'p', text: '{/clause_tag}' },
          { style: 'p', text: '{#clause_drag}' },
          { style: 'h1', text: 'Article — Obligation de sortie conjointe (drag along)' },
          { style: 'p', text: "En cas d'offre d'un tiers de bonne foi portant sur 100 % des titres de la Société, acceptée par des Parties représentant au moins la majorité des titres, chaque autre Partie s'engage irrévocablement à céder la totalité de ses titres au tiers acquéreur aux mêmes conditions, notamment de prix." },
          { style: 'p', text: '{/clause_drag}' },
          { style: 'p', text: '{#clause_non_concurrence}' },
          { style: 'h1', text: 'Article — Non-concurrence' },
          { style: 'p', text: "Chaque Partie exerçant des fonctions opérationnelles au sein de la Société s'interdit, pendant la durée du pacte et pendant deux (2) années suivant la perte de sa qualité d'associé, d'exercer directement ou indirectement une activité concurrente de celle de la Société sur le territoire où celle-ci opère." },
          { style: 'p', text: '{/clause_non_concurrence}' },
          { style: 'h1', text: 'Article — Information' },
          { style: 'p', text: "La direction communiquera aux Parties, au moins une fois par an, les comptes annuels et un état d'avancement de l'activité, et les informera sans délai de tout événement significatif." },
          { style: 'h1', text: 'Article — Confidentialité et loi applicable' },
          { style: 'p', text: "Le présent pacte est confidentiel. Il est régi par le droit français ; tout litige relatif à sa validité, son interprétation ou son exécution relèvera du tribunal de commerce du siège de la Société." },
          { style: 'p', text: 'Fait le {date_pacte_fmt}, en autant d’exemplaires que de Parties.' },
          { style: 'p', text: '{#parties}' },
          { style: 'sign', text: '{nom_complet}' },
          { style: 'p', text: '{/parties}' },
        ],
      },
      {
        code: 'bordereau_adhesion', nom: "Bordereau d'adhésion au pacte", obligatoire: false,
        template: [
          { style: 'title', text: 'BORDEREAU D’ADHÉSION AU PACTE D’ASSOCIÉS' },
          { style: 'p', text: 'Je soussigné(e) ______________________________, devenant associé de la société {societe_denomination}, déclare avoir pris connaissance du pacte d’associés conclu le {date_pacte_fmt} entre les associés de la Société et y adhérer sans réserve, avec tous les droits et obligations qui en découlent.' },
          { style: 'p', text: 'Fait le ____________________.' },
          { style: 'sign', text: 'Signature, précédée de la mention « Bon pour adhésion »' },
        ],
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  approbation_comptes: {
    libelle: 'Approbation des comptes annuels',
    variables: [
      { name: 'exercice_clos', label: "Date de clôture de l'exercice", type: 'date', required: true },
      { name: 'date_ago', label: "Date de l'assemblée générale", type: 'date', required: true },
      { name: 'resultat', label: "Résultat de l'exercice (€, négatif si perte)", type: 'number', required: true },
      { name: 'affectation', label: 'Affectation du résultat', type: 'select', required: true, options: [
        { value: 'ran', label: 'Report à nouveau' },
        { value: 'dividendes', label: 'Distribution de dividendes' },
        { value: 'reserve', label: 'Réserve légale puis report à nouveau' },
      ] },
      { name: 'montant_dividendes', label: 'Montant distribué (€)', type: 'number', showIf: 'affectation:dividendes' },
      { name: 'conventions_reglementees', label: 'Conventions réglementées à approuver', type: 'checkbox', default: false },
      { name: 'quitus', label: 'Quitus à la direction', type: 'checkbox', default: true },
    ],
    documents: [
      {
        code: 'convocation', nom: "Convocation à l'assemblée", obligatoire: true,
        template: [
          ...EN_TETE_SOCIETE,
          { style: 'title', text: 'CONVOCATION À L’ASSEMBLÉE GÉNÉRALE ORDINAIRE ANNUELLE' },
          { style: 'p', text: 'Madame, Monsieur,' },
          { style: 'p', text: "Nous avons l'honneur de vous convoquer à l'assemblée générale ordinaire annuelle de la société {societe_denomination}, qui se tiendra le {date_ago_fmt} au siège social, à l'effet de délibérer sur l'ordre du jour suivant :" },
          { style: 'p', text: "- Rapport de gestion de la direction ; approbation des comptes de l'exercice clos le {exercice_clos_fmt} ;" },
          { style: 'p', text: '- Affectation du résultat ;' },
          { style: 'p', text: '{#conventions_reglementees}- Approbation des conventions réglementées ;{/conventions_reglementees}' },
          { style: 'p', text: '{#quitus}- Quitus à la direction ;{/quitus}' },
          { style: 'p', text: '- Pouvoirs pour formalités.' },
          { style: 'p', text: "Les comptes annuels, le rapport de gestion et le texte des résolutions proposées sont tenus à votre disposition au siège social et vous seront adressés sur demande." },
          { style: 'sign', text: '{dirigeant_nom_complet}, {dirigeant_fonction}' },
        ],
      },
      {
        code: 'rapport_gestion', nom: 'Rapport de gestion', obligatoire: true,
        template: [
          ...EN_TETE_SOCIETE,
          { style: 'title', text: 'RAPPORT DE GESTION' },
          { style: 'center', text: "Sur les opérations de l'exercice clos le {exercice_clos_fmt}" },
          { style: 'p', text: "Chers associés, nous vous avons réunis en assemblée générale ordinaire annuelle afin de vous rendre compte de l'activité de la société {societe_denomination} au cours de l'exercice clos le {exercice_clos_fmt} et de soumettre à votre approbation les comptes dudit exercice." },
          { style: 'h1', text: "1. Activité et résultats de l'exercice" },
          { style: 'p', text: "L'exercice clos le {exercice_clos_fmt} se solde par un résultat de {resultat_fmt} euros. [Compléter : faits marquants, évolution de l'activité, événements postérieurs à la clôture, perspectives.]" },
          { style: 'h1', text: '2. Affectation du résultat' },
          { style: 'p', text: '{#affectation_ran}Nous vous proposons d’affecter le résultat de l’exercice, soit {resultat_fmt} euros, en totalité au compte « report à nouveau ».{/affectation_ran}' },
          { style: 'p', text: '{#affectation_reserve}Nous vous proposons d’affecter le résultat de l’exercice, soit {resultat_fmt} euros, à hauteur de 5 % à la réserve légale et le solde au compte « report à nouveau ».{/affectation_reserve}' },
          { style: 'p', text: '{#affectation_dividendes}Nous vous proposons de distribuer à titre de dividendes la somme de {montant_dividendes_fmt} euros et d’affecter le solde du résultat au compte « report à nouveau ».{/affectation_dividendes}' },
          { style: 'p', text: '{#conventions_reglementees}' },
          { style: 'h1', text: '3. Conventions réglementées' },
          { style: 'p', text: "Nous vous demandons d'approuver les conventions visées à l'article L. 227-10 du Code de commerce conclues ou poursuivies au cours de l'exercice, dont la liste vous a été communiquée." },
          { style: 'p', text: '{/conventions_reglementees}' },
          { style: 'p', text: "Nous vous invitons à adopter les résolutions qui vous sont soumises." },
          { style: 'sign', text: '{dirigeant_nom_complet}, {dirigeant_fonction}' },
        ],
      },
      {
        code: 'pv_ago', nom: "PV de l'assemblée générale ordinaire", obligatoire: true,
        template: [
          ...EN_TETE_SOCIETE,
          { style: 'title', text: 'PROCÈS-VERBAL DE L’ASSEMBLÉE GÉNÉRALE ORDINAIRE ANNUELLE' },
          { style: 'center', text: 'Du {date_ago_fmt}' },
          { style: 'p', text: "L'an et le jour susdits, les associés de la société {societe_denomination} se sont réunis en assemblée générale ordinaire annuelle au siège social, sur convocation de la direction. La feuille de présence permet de constater que l'assemblée peut valablement délibérer." },
          { style: 'h1', text: 'Première résolution — Approbation des comptes' },
          { style: 'p', text: "L'assemblée générale, après avoir entendu la lecture du rapport de gestion, approuve les comptes annuels de l'exercice clos le {exercice_clos_fmt} tels qu'ils lui ont été présentés, faisant ressortir un résultat de {resultat_fmt} euros, ainsi que les opérations traduites dans ces comptes." },
          { style: 'p', text: 'Cette résolution est adoptée à l’unanimité.' },
          { style: 'h1', text: 'Deuxième résolution — Affectation du résultat' },
          { style: 'p', text: '{#affectation_ran}L’assemblée générale décide d’affecter le résultat de l’exercice, soit {resultat_fmt} euros, en totalité au compte « report à nouveau ».{/affectation_ran}' },
          { style: 'p', text: '{#affectation_reserve}L’assemblée générale décide d’affecter 5 % du résultat de l’exercice à la réserve légale et le solde, sur un résultat de {resultat_fmt} euros, au compte « report à nouveau ».{/affectation_reserve}' },
          { style: 'p', text: '{#affectation_dividendes}L’assemblée générale décide de distribuer aux associés, à titre de dividendes, la somme de {montant_dividendes_fmt} euros, le solde étant affecté au compte « report à nouveau ». Ce dividende sera mis en paiement dans les délais légaux.{/affectation_dividendes}' },
          { style: 'p', text: 'Cette résolution est adoptée à l’unanimité.' },
          { style: 'p', text: '{#conventions_reglementees}' },
          { style: 'h1', text: 'Résolution — Conventions réglementées' },
          { style: 'p', text: "L'assemblée générale approuve les conventions visées à l'article L. 227-10 du Code de commerce, les associés intéressés ne prenant pas part au vote." },
          { style: 'p', text: '{/conventions_reglementees}' },
          { style: 'p', text: '{#quitus}' },
          { style: 'h1', text: 'Résolution — Quitus' },
          { style: 'p', text: "L'assemblée générale donne quitus entier et sans réserve à la direction pour l'exécution de son mandat au titre de l'exercice écoulé. Cette résolution est adoptée à l'unanimité." },
          { style: 'p', text: '{/quitus}' },
          { style: 'h1', text: 'Résolution finale — Pouvoirs' },
          { style: 'p', text: "Tous pouvoirs sont donnés au porteur d'une copie ou d'un extrait du présent procès-verbal pour accomplir toutes formalités, notamment le dépôt des comptes au greffe." },
          { style: 'p', text: "Plus rien n'étant à l'ordre du jour, la séance est levée. De tout ce que dessus, il a été dressé le présent procès-verbal signé après lecture." },
          { style: 'sign', text: '{dirigeant_nom_complet}, {dirigeant_fonction}' },
        ],
      },
      {
        code: 'feuille_presence', nom: 'Feuille de présence', obligatoire: true,
        template: [
          ...EN_TETE_SOCIETE,
          { style: 'title', text: 'FEUILLE DE PRÉSENCE' },
          { style: 'center', text: 'Assemblée générale ordinaire annuelle du {date_ago_fmt}' },
          { style: 'p', text: '{#associes}' },
          { style: 'p', text: '{nom_complet} — {nb_titres} titres ({pourcentage} %) — Présent / Représenté — Signature : ______________' },
          { style: 'p', text: '{/associes}' },
          { style: 'p', text: 'Total des titres présents ou représentés : {societe_nb_titres} sur {societe_nb_titres}.' },
          { style: 'p', text: 'Feuille de présence certifiée exacte par le président de séance.' },
          { style: 'sign', text: '{dirigeant_nom_complet}, {dirigeant_fonction}' },
        ],
      },
      {
        code: 'pouvoir_ago', nom: 'Pouvoir de représentation', obligatoire: false,
        template: [
          { style: 'title', text: 'POUVOIR' },
          { style: 'p', text: 'Je soussigné(e) ______________________________, associé de la société {societe_denomination}, titulaire de __________ titres,' },
          { style: 'p', text: 'donne pouvoir à ______________________________ de me représenter à l’assemblée générale ordinaire annuelle du {date_ago_fmt}, de prendre part à toutes délibérations et de voter en mon nom sur les résolutions inscrites à l’ordre du jour.' },
          { style: 'p', text: 'Fait le ____________________.' },
          { style: 'sign', text: 'Signature, précédée de la mention « Bon pour pouvoir »' },
        ],
      },
    ],
  },
};

module.exports = { OPERATION_TYPES };
